version: "3"
services:
  app:
    build: .
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    build: ./db/
    env_file:
      - .env
    restart: always
